-- Viyra.com™ schema scaffold
create table if not exists roles (id uuid primary key default gen_random_uuid(), name text unique not null, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists profiles (id uuid primary key, role text not null, country text, preferred_language text default 'en', verification_status text default 'pending', kyc_status text default 'pending', market_access text[] default '{}', created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid, deleted_at timestamptz);
create table if not exists markets (code text primary key, name text, currency text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists properties (id uuid primary key default gen_random_uuid(), realtor_id uuid, market_code text references markets(code), title text, price numeric, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid, deleted_at timestamptz);
create table if not exists property_images (id uuid primary key default gen_random_uuid(), property_id uuid references properties(id), url text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists property_features (id uuid primary key default gen_random_uuid(), property_id uuid references properties(id), feature_key text, feature_value text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists buyer_preferences (id uuid primary key default gen_random_uuid(), buyer_id uuid, payload jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists ai_match_results (id uuid primary key default gen_random_uuid(), buyer_preference_id uuid, property_id uuid, score int, explanation text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists offers (id uuid primary key default gen_random_uuid(), property_id uuid, buyer_id uuid, seller_id uuid, amount numeric, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid, deleted_at timestamptz);
create table if not exists transactions (id uuid primary key default gen_random_uuid(), property_id uuid, buyer_id uuid, seller_id uuid, status text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists transaction_stages (id uuid primary key default gen_random_uuid(), transaction_id uuid, stage_key text, status text, responsible_role text, due_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists transaction_documents (id uuid primary key default gen_random_uuid(), transaction_id uuid, document_type text, status text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists notifications (id uuid primary key default gen_random_uuid(), user_id uuid, body text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists messages (id uuid primary key default gen_random_uuid(), from_user uuid, to_user uuid, body text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists legal_workflows (id uuid primary key default gen_random_uuid(), market_code text, payload jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists agent_logs (id uuid primary key default gen_random_uuid(), transaction_id uuid, severity text, message text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid, action text, resource_type text, resource_id text, metadata jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists saved_properties (id uuid primary key default gen_random_uuid(), user_id uuid, property_id uuid, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists favorites (id uuid primary key default gen_random_uuid(), user_id uuid, property_id uuid, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists realtor_clients (id uuid primary key default gen_random_uuid(), realtor_id uuid, client_id uuid, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists viewing_requests (id uuid primary key default gen_random_uuid(), property_id uuid, buyer_id uuid, status text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists kyc_records (id uuid primary key default gen_random_uuid(), user_id uuid, status text, provider text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists signature_requests (id uuid primary key default gen_random_uuid(), transaction_id uuid, provider text, status text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);

alter table profiles enable row level security;
-- RLS placeholders:
-- buyers see own records; sellers own listings; realtors assigned entities; lawyers/notaries assigned transactions; admins elevated.
create table if not exists users (id uuid primary key, email text unique, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists agencies (id uuid primary key default gen_random_uuid(), name text, country text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists realtor_users (id uuid primary key default gen_random_uuid(), agency_id uuid references agencies(id), profile_id uuid references profiles(id), created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists buyer_profiles (id uuid primary key default gen_random_uuid(), profile_id uuid references profiles(id), risk_appetite text, intent text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists property_matches (id uuid primary key default gen_random_uuid(), buyer_profile_id uuid references buyer_profiles(id), property_id uuid references properties(id), score int, explanation text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists deal_rooms (id uuid primary key default gen_random_uuid(), transaction_id uuid references transactions(id), visibility text default 'private', created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists deal_room_messages (id uuid primary key default gen_random_uuid(), deal_room_id uuid references deal_rooms(id), sender_id uuid, message text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists documents (id uuid primary key default gen_random_uuid(), owner_id uuid, doc_type text, storage_path text, status text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid, deleted_at timestamptz);
create table if not exists subscriptions (id uuid primary key default gen_random_uuid(), account_id uuid, plan text, provider text, status text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists payment_providers (id uuid primary key default gen_random_uuid(), name text unique, enabled boolean default false, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists payments (id uuid primary key default gen_random_uuid(), user_id uuid, provider text, amount numeric, currency text, status text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists invoices (id uuid primary key default gen_random_uuid(), payment_id uuid references payments(id), invoice_no text, total numeric, currency text, issued_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists commissions (id uuid primary key default gen_random_uuid(), property_id uuid references properties(id), realtor_pct numeric, platform_pct numeric, success_fee_rule text, concierge_fee numeric, referral_rule text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists featured_listings (id uuid primary key default gen_random_uuid(), property_id uuid references properties(id), starts_at timestamptz, ends_at timestamptz, rank_weight int default 0, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists concierge_requests (id uuid primary key default gen_random_uuid(), buyer_id uuid, topic text, status text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists referral_partners (id uuid primary key default gen_random_uuid(), category text, name text, market_code text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists compliance_events (id uuid primary key default gen_random_uuid(), user_id uuid, event_type text, metadata jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists crypto_payment_intents (id uuid primary key default gen_random_uuid(), user_id uuid, asset text, network text, amount numeric, fx_snapshot jsonb, status text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists ledger_entries (id uuid primary key default gen_random_uuid(), account_ref text, currency text, debit numeric, credit numeric, reference_type text, reference_id text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
