-- Luxary Realtor™ schema scaffold
create table if not exists roles (id uuid primary key default gen_random_uuid(), name text unique not null, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists profiles (id uuid primary key, role text not null, country text, preferred_language text default 'en', verification_status text default 'pending', kyc_status text default 'pending', market_access text[] default '{}', created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid, deleted_at timestamptz);
create table if not exists markets (code text primary key, name text, currency text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists properties (id uuid primary key default gen_random_uuid(), realtor_id uuid, market_code text references markets(code), title text, price numeric, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid, deleted_at timestamptz);
create table if not exists property_images (id uuid primary key default gen_random_uuid(), property_id uuid references properties(id), url text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists property_features (id uuid primary key default gen_random_uuid(), property_id uuid references properties(id), feature_key text, feature_value text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists buyer_preferences (id uuid primary key default gen_random_uuid(), buyer_id uuid, payload jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists ai_match_results (id uuid primary key default gen_random_uuid(), buyer_preference_id uuid, property_id uuid, score int, explanation text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists offers (id uuid primary key default gen_random_uuid(), property_id uuid, buyer_id uuid, seller_id uuid, amount numeric, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid, deleted_at timestamptz);
create table if not exists transactions (id uuid primary key default gen_random_uuid(), property_id uuid, buyer_id uuid, seller_id uuid, status text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists transaction_stages (id uuid primary key default gen_random_uuid(), transaction_id uuid, stage_key text, status text, responsible_role text, due_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists transaction_documents (id uuid primary key default gen_random_uuid(), transaction_id uuid, document_type text, status text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists notifications (id uuid primary key default gen_random_uuid(), user_id uuid, body text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists messages (id uuid primary key default gen_random_uuid(), from_user uuid, to_user uuid, body text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists legal_workflows (id uuid primary key default gen_random_uuid(), market_code text, payload jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists agent_logs (id uuid primary key default gen_random_uuid(), transaction_id uuid, severity text, message text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid, action text, resource_type text, resource_id text, metadata jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists saved_properties (id uuid primary key default gen_random_uuid(), user_id uuid, property_id uuid, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists favorites (id uuid primary key default gen_random_uuid(), user_id uuid, property_id uuid, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists realtor_clients (id uuid primary key default gen_random_uuid(), realtor_id uuid, client_id uuid, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists viewing_requests (id uuid primary key default gen_random_uuid(), property_id uuid, buyer_id uuid, status text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists kyc_records (id uuid primary key default gen_random_uuid(), user_id uuid, status text, provider text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);
create table if not exists signature_requests (id uuid primary key default gen_random_uuid(), transaction_id uuid, provider text, status text, created_at timestamptz default now(), updated_at timestamptz default now(), created_by uuid);

alter table profiles enable row level security;
-- RLS placeholders:
-- buyers see own records; sellers own listings; realtors assigned entities; lawyers/notaries assigned transactions; admins elevated.
